export const courierProviders = [
  { name: "Fedex ", link: "fedex-tracking" },
  { name: "USPS Courier", link: "usps-courier-tracking" },
  { name: "Blue Dart Courier ", link: "blue-dart-courier-tracking" },
  { name: "UPS Courier", link: "ups-courier-tracking" },
  {
    name: "Professional Courier",
    link: "professional-courier-tracking",
  },
  { name: "Delhivery Courier", link: "delhivery-courier-tracking" },
  {
    name: "Skynet Worldwide express",
    link: "skynet-worldwide-express-tracking",
  },
  { name: "DTDC Courier ", link: "dtdc-courier-tracking" },
  { name: "Digital Delivery ", link: "digital-delivery-courier-tracking" },

  { name: "Anjani Courier", link: "anjani-courier-tracking" },
  { name: "CNE Express Courier", link: "cne-express-courier-tracking" },
  { name: "DTDC USA ", link: "dtdc-usa-tracking" },
  { name: "St Courier ", link: "st-courier-tracking" },
  { name: "Skyking Courer", link: "skyking-courier-tracking" },
  { name: "Spee Dee Delivery ", link: "spee-dee-delivery-tracking" },

  {
    name: "Citi Network Courier",
    link: "citi-network-courier-tracking",
  },
  {
    name: "17 Post Service Courier",
    link: "17-post-service-courier-tracking",
  },
  { name: "2go Courier", link: "2go-courier-tracking" },
  { name: "360 Lion Courier", link: "360-lion-courier-tracking" },
  {
    name: "4-72 Entregando Courier",
    link: "4-72-entregando-courier-tracking",
  },
  { name: "4px Courier", link: "4px-courier-tracking" },
  {
    name: "4square Group Courier",
    link: "4square-group-courier-tracking",
  },
  {
    name: "7 Horse Logistics Courier",
    link: "7-horse-logistics-courier-tracking",
  },
  {
    name: "A1 International Courier",
    link: "a1-international-courier-tracking",
  },
  { name: "A3 Express Courier", link: "a3-express-courier-tracking" },
  {
    name: "AAA Cooper Transportation Courier",
    link: "aaa-cooper-transportation-courier-tracking",
  },
  {
    name: "Aact freight shipment",
    link: "aact-freight-shipment-tracking",
  },
  {
    name: "ABC Transport Courier",
    link: "abc-transport-courier-tracking",
  },
  { name: "ABF Freight", link: "abf-freight-tracking" },
  { name: "ABX Express Courier", link: "abx-express-courier-tracking" },
  {
    name: "Accurate Freight Carrier",
    link: "accurate-freight-carrier-tracking",
  },
  { name: "ACE Courier", link: "ace-courier-tracking" },
  { name: "ACS Courier", link: "acs-courier-tracking" },
  { name: "ACX Courier", link: "acx-courier-tracking" },
  {
    name: "Adicional Logistics Courier",
    link: "adicional-logistics-courier-tracking",
  },
  {
    name: "Aditya Express Courier",
    link: "aditya-express-courier-tracking",
  },
  { name: "ADS One Courier", link: "ads-one-courier-tracking" },
  { name: "Air King Courier", link: "air-king-courier-tracking" },
  {
    name: "Air Star Xpress Courier",
    link: "air-star-xpress-courier-tracking",
  },
  { name: "Air State Courier", link: "air-state-courier-tracking" },
  { name: "Air21 Courier", link: "air21-courier-tracking" },
  {
    name: "Airbase Express Courier",
    link: "airbase-express-courier-tracking",
  },
  {
    name: "Airpak Express Courier",
    link: "airpak-express-courier-tracking",
  },
  { name: "Airspeed Courier", link: "airspeed-courier-tracking" },
  { name: "Airstate Courier", link: "airstate-courier-tracking" },
  { name: "Airwings Courier ", link: "airwings-courier-tracking" },
  { name: "AJ Express Courier", link: "aj-express-courier-tracking" },
  {
    name: "Ajay Logistics Goods Courier",
    link: "ajay-logistics-goods-courier-tracking",
  },
  { name: "AJW Courier", link: "ajw-courier-tracking" },
  { name: "AJW Express Courier", link: "ajw-express-courier-tracking" },
  {
    name: "Akash Ganga Courier ",
    link: "akash-ganga-courier-tracking",
  },
  { name: "Akashdoot Courier", link: "akashdoot-courier-tracking" },
  { name: "AKR Express Courier", link: "akr-express-courier-tracking" },
  { name: "Albanian Courier", link: "albanian-courier-tracking" },
  {
    name: "Ample Express Courier",
    link: "ample-express-courier-tracking",
  },
  { name: "AMS Courier", link: "ams-courier-tracking" },
  { name: "An Post Courier", link: "an-post-courier-tracking" },

  {
    name: "Apc Overnight Courier",
    link: "apc-overnight-courier-tracking",
  },
  { name: "Apc Postal", link: "apc-postal-tracking" },
  {
    name: "Apc Postal Logistics Courier",
    link: "apc-postal-logistics-courier-tracking",
  },
  { name: "Apex Courier", link: "apex-courier-tracking" },
  { name: "AR Express Courier", link: "ar-express-courier-tracking" },
  {
    name: "Aramex Australia Courier",
    link: "aramex-australia-courier-tracking",
  },
  { name: "Aramex Courier ", link: "aramex-courier-tracking" },
  { name: "Arc Carrier ", link: "arc-carrier-tracking" },
  { name: "Arrow XL Courier", link: "arrow-xl-courier-tracking" },
  {
    name: "Asendia Germany Courier",
    link: "asendia-germany-courier-tracking",
  },
  { name: "Asendia HK Courier", link: "asendia-hk-courier-tracking" },
  { name: "Asendia UK Courier", link: "asendia-uk-courier-tracking" },
  { name: "Asendia USA Courier", link: "asendia-usa-courier-tracking" },
  { name: "ASM Courier", link: "asm-courier-tracking" },
  {
    name: "ASMI Express Courier",
    link: "asmi-express-courier-tracking",
  },
  { name: "Asurion shipment", link: "asurion-shipment-tracking" },
  { name: "ATS Amazon Shipping", link: "ats-amazon-shipping-tracking" },
  { name: "Ats Courier ", link: "ats-courier-tracking" },
  {
    name: "AU Post China Courier",
    link: "au-post-china-courier-tracking",
  },
  {
    name: "Australia Express Post Courier",
    link: "australia-express-post-courier-tracking",
  },
  {
    name: "Austrian Post Courier",
    link: "austrian-post-courier-tracking",
  },
  {
    name: "Austrian post international",
    link: "austrian-post-international-tracking",
  },
  {
    name: "Averitt Express Courier",
    link: "averitt-express-courier-tracking",
  },
  {
    name: "Avinash Carier Transport Acpl Courier",
    link: "avinash-carier-transport-acpl-courier-tracking",
  },
  { name: "B2C Europe Courier", link: "b2c-europe-courier-tracking" },
  { name: "B4 Express Courier", link: "b4-express-courier-tracking" },
  { name: "Babies r us", link: "babies-r-us-order-tracking" },
  {
    name: "Bed bath and beyond",
    link: "bed-bath-and-beyond-order-tracking",
  },
  {
    name: "Belgium Post Courier",
    link: "belgium-post-courier-tracking",
  },
  { name: "Belpost belarus", link: "belpost-belarus-tracking" },
  { name: "Belpost Courier", link: "belpost-courier-tracking" },
  {
    name: "Bert Transport Courier",
    link: "bert-transport-courier-tracking",
  },
  {
    name: "Best Express Courier",
    link: "best-express-courier-tracking",
  },
  {
    name: "Better Trucks Courier",
    link: "better-trucks-courier-tracking",
  },
  {
    name: "Bharat Motor Parcel Courier",
    link: "bharat-motor-parcel-courier-tracking",
  },
  { name: "Bhavani Courier", link: "bhavani-courier-tracking" },
  { name: "Big Guy Courier", link: "big-guy-courier-tracking" },
  { name: "BMP Surface Courier", link: "bmp-surface-courier-tracking" },
  { name: "BNL Courier", link: "bnl-courier-tracking" },
  { name: "Bom-gim Courier ", link: "bom-gim-courier-tracking" },
  {
    name: "Bombay Gujarat Transport Courier",
    link: "bombay-gujarat-transport-courier-tracking",
  },
  { name: "Bombino Courier", link: "bombino-courier-tracking" },
  { name: "Bonds Courier", link: "bonds-courier-tracking" },
  {
    name: "Bonds Logistics Courier",
    link: "bonds-logistics-courier-tracking",
  },
  {
    name: "Book My Packet Courier",
    link: "book-my-packet-courier-tracking",
  },
  { name: "Border Express", link: "border-express-tracking" },
  { name: "Boxc Courier", link: "boxc-courier-tracking" },
  { name: "BPL Cargo Courier", link: "bpl-cargo-courier-tracking" },
  { name: "Bpost Courier", link: "bpost-courier-tracking" },
  {
    name: "Bpost International Courier",
    link: "bpost-international-courier-tracking",
  },
  {
    name: "Brandt Truck Line Courier",
    link: "brandt-truck-line-courier-tracking",
  },
  {
    name: "Brazil Correios Courier",
    link: "brazil-correios-courier-tracking",
  },
  { name: "Bright Courier", link: "bright-courier-tracking" },
  {
    name: "Brizo Global Cargo Courier",
    link: "brizo-global-cargo-courier-tracking",
  },
  {
    name: "BRT Bartolini Courier",
    link: "brt-bartolini-courier-tracking",
  },
  { name: "Budget Courier", link: "budget-courier-tracking" },
  { name: "Bulgarian posts", link: "bulgarian-posts-tracking" },
  { name: "Buylogic Courier", link: "buylogic-courier-tracking" },
  { name: "C & T Courier", link: "c-&-t-courier-tracking" },
  {
    name: "Cambodia Post Courier",
    link: "cambodia-post-courier-tracking",
  },
  { name: "Canada Post", link: "canada-post-tracking" },
  { name: "Canpar Courier", link: "canpar-courier-tracking" },
  {
    name: "Canpar Courier Courier",
    link: "canpar-courier-courier-tracking",
  },
  { name: "Caper Courier", link: "caper-courier-tracking" },
  {
    name: "CBL Logistics Courier",
    link: "cbl-logistics-courier-tracking",
  },
  { name: "CCI Courier", link: "cci-courier-tracking" },
  {
    name: "Central Freight Lines Courier",
    link: "central-freight-lines-courier-tracking",
  },
  { name: "CEVA Logistics", link: "ceva-logistics-tracking" },
  {
    name: "Chetak Logistics Courier",
    link: "chetak-logistics-courier-tracking",
  },
  { name: "China EMS Courier", link: "china-ems-courier-tracking" },
  { name: "China Post Courier", link: "china-post-courier-tracking" },
  {
    name: "Chronopost France Courier",
    link: "chronopost-france-courier-tracking",
  },
  {
    name: "Chronopost Portugal Courier",
    link: "chronopost-portugal-courier-tracking",
  },

  { name: "Citipost Courier", link: "citipost-courier-tracking" },
  { name: "Citipost Courier ", link: "citipost-courier-tracking" },
  {
    name: "City Express Courier",
    link: "city-express-courier-tracking",
  },
  {
    name: "City Express Courier ",
    link: "city-express-courier-tracking",
  },
  { name: "City Link Courier", link: "city-link-courier-tracking" },
  {
    name: "City Link Express Courier",
    link: "city-link-express-courier-tracking",
  },
  {
    name: "City Link International Courier",
    link: "city-link-international-courier-tracking",
  },
  { name: "CJ Gls Courier", link: "cj-gls-courier-tracking" },
  { name: "CJ Packet", link: "cj-packet-tracking" },
  { name: "Classic Courier", link: "classic-courier-tracking" },
  { name: "CMA CGM Courier", link: "cma-cgm-courier-tracking" },
  { name: "Colis Privé Courier", link: "colis-privé-courier-tracking" },
  { name: "Colissimo Courier", link: "colissimo-courier-tracking" },
  { name: "Collect Courier", link: "collect-courier-tracking" },
  { name: "Collect+ Courier", link: "collect+-courier-tracking" },
  { name: "Combined Courier", link: "combined-courier-tracking" },
  {
    name: "Con-Way Freight Courier",
    link: "con-way-freight-courier-tracking",
  },
  { name: "Concor Courier", link: "concor-courier-tracking" },
  {
    name: "Connectindia Courier",
    link: "connectindia-courier-tracking",
  },
  { name: "Continental Courier", link: "continental-courier-tracking" },
  { name: "Corporate Express ", link: "corporate-express-tracking" },
  { name: "Correis Courier", link: "correis-courier-tracking" },
  { name: "Correo argentino", link: "correo-argentino-tracking" },
  {
    name: "Correo Argentino Courier",
    link: "correo-argentino-courier-tracking",
  },
  {
    name: "Correos Chile Courier",
    link: "correos-chile-courier-tracking",
  },
  {
    name: "Correos De EspañA Courier",
    link: "correos-de-españa-courier-tracking",
  },
  {
    name: "Correos De Mexico Courier",
    link: "correos-de-mexico-courier-tracking",
  },
  {
    name: "Correos Express Courier",
    link: "correos-express-courier-tracking",
  },
  { name: "Cosco Courier", link: "cosco-courier-tracking" },
  {
    name: "Cosmetics Now Courier",
    link: "cosmetics-now-courier-tracking",
  },
  { name: "Cosmic Courier", link: "cosmic-courier-tracking" },
  { name: "Costco", link: "costco-order-tracking" },
  {
    name: "Country Wide Courier",
    link: "country-wide-courier-tracking",
  },
  { name: "Courex Courier", link: "courex-courier-tracking" },
  { name: "Courier It Courier", link: "courier-it-courier-tracking" },
  {
    name: "Courier Network Courier",
    link: "courier-network-courier-tracking",
  },
  { name: "Courier NZ Courier", link: "courier-nz-courier-tracking" },
  {
    name: "Courier Plus Courier",
    link: "courier-plus-courier-tracking",
  },
  {
    name: "Courier Post Courier",
    link: "courier-post-courier-tracking",
  },
  { name: "Couriers Please ", link: "couriers-please-tracking" },
  { name: "Cpacket Courier", link: "cpacket-courier-tracking" },
  {
    name: "Cpc canadapost corporation package",
    link: "cpc-canada-post-corporation-package-tracking",
  },
  {
    name: "Crown World Wide Courier",
    link: "crown-world-wide-courier-tracking",
  },
  { name: "CTT Courier", link: "ctt-courier-tracking" },
  {
    name: "Cuckoo Express Courier",
    link: "cuckoo-express-courier-tracking",
  },
  { name: "Cyprus post", link: "cyprus-post-tracking" },
  { name: "Cyprus Post Courier", link: "cyprus-post-courier-tracking" },
  { name: "Czech republic post", link: "czech-republic-post-tracking" },
  { name: "Dachser Courier", link: "dachser-courier-tracking" },
  {
    name: "Dats Trucking Courier",
    link: "dats-trucking-courier-tracking",
  },
  { name: "Dawn Wing Courier", link: "dawn-wing-courier-tracking" },
  {
    name: "Dayton Freight Lines Courier",
    link: "dayton-freight-lines-courier-tracking",
  },
  {
    name: "DB Schenker Sweden Courier",
    link: "db-schenker-sweden-courier-tracking",
  },
  { name: "Deb Air Courier", link: "deb-air-courier-tracking" },
  {
    name: "Deccan Queen Courier",
    link: "deccan-queen-courier-tracking",
  },
  { name: "Delcart Courier ", link: "delcart-courier-tracking" },
  { name: "Delex Courier ", link: "delex-courier-tracking" },
  {
    name: "Delivree King Courier",
    link: "delivree-king-courier-tracking",
  },
  { name: "Delnet Express ", link: "delnet-express-tracking" },
  { name: "Deltec Courier", link: "deltec-courier-tracking" },
  { name: "Detrack Courier", link: "detrack-courier-tracking" },
  { name: "Deutsche Post Dhl ", link: "deutsche-post-dhl-tracking" },
  {
    name: "Deutsche Post Mail Courier",
    link: "deutsche-post-mail-courier-tracking",
  },
  {
    name: "Deutscsche Post Courier",
    link: "deutscsche-post-courier-tracking",
  },
  {
    name: "Dg Global Forwarding Courier",
    link: "dg-global-forwarding-courier-tracking",
  },
  { name: "DHL Active Tracing", link: "dhl-active-tracing-tracking" },
  { name: "DHL Courier", link: "dhl-courier-tracking" },
  { name: "DHL Ecommerce Asia", link: "dhl-ecommerce-asia-tracking" },
  { name: "DHL Express", link: "dhl-express-tracking" },
  {
    name: "DHL Global Forwarding",
    link: "dhl-global-forwarding-tracking",
  },
  { name: "DHL Global Mail", link: "dhl-global-mail-tracking" },
  { name: "DHL Express PieceId", link: "dhl-express-pieceid-tracking" },
  { name: "Diacom Canada", link: "diacom-canada-tracking" },
  { name: "Dinland Courier", link: "dinland-courier-tracking" },
  {
    name: "Direct Freight Express Courier",
    link: "direct-freight-express-courier-tracking",
  },
  { name: "Direct Link Courier", link: "direct-link-courier-tracking" },
  {
    name: "Direct Way Cargo Courier",
    link: "direct-way-cargo-courier-tracking",
  },
  { name: "Disney store", link: "disney-store-order-tracking" },
  { name: "Divine Courier", link: "divine-courier-tracking" },
  { name: "Dji", link: "dji-order-tracking" },
  { name: "DMM Network Courier", link: "dmm-network-courier-tracking" },
  { name: "DNX Cargo Courier", link: "dnx-cargo-courier-tracking" },
  {
    name: "Dohrn Transfer Company Courier",
    link: "dohrn-transfer-company-courier-tracking",
  },
  { name: "Dotzot Courier ", link: "dotzot-courier-tracking" },
  { name: "DPD  UK", link: "dpd-uk-tracking" },
  { name: "DPD Courier", link: "dpd-courier-tracking" },
  { name: "DPD US", link: "dpd-us-tracking" },
  { name: "DPE Express Courier", link: "dpe-express-courier-tracking" },
  {
    name: "Dpe South Africa Courier",
    link: "dpe-south-africa-courier-tracking",
  },
  {
    name: "Dpex Worldwide Courier",
    link: "dpex-worldwide-courier-tracking",
  },
  { name: "DRP Courier", link: "drp-courier-tracking" },
  { name: "DRTC Courier", link: "drtc-courier-tracking" },
  { name: "DSV Courier", link: "dsv-courier-tracking" },
  { name: "DTDC Australia ", link: "dtdc-australia-tracking" },
  {
    name: "DTDC Express Global ",
    link: "dtdc-express-global-tracking",
  },
  { name: "DTDC Singapore ", link: "dtdc-singapore-tracking" },
  { name: "DTDC UAE ", link: "dtdc-uae-tracking" },
  { name: "Dtrans Courier", link: "dtrans-courier-tracking" },
  { name: "Durga Courier", link: "durga-courier-tracking" },
  { name: "DX Delivery Courier", link: "dx-delivery-courier-tracking" },
  {
    name: "Dynamic Logistics Courier",
    link: "dynamic-logistics-courier-tracking",
  },
  {
    name: "Dynamic Parcel Courier",
    link: "dynamic-parcel-courier-tracking",
  },
  { name: "Eagle Courier", link: "eagle-courier-tracking" },
  { name: "Eastern Air Courier", link: "eastern-air-courier-tracking" },
  {
    name: "Easy Courier Courier",
    link: "easy-courier-courier-tracking",
  },
  { name: "Easy Mail Courier", link: "easy-mail-courier-tracking" },
  {
    name: "Ebay international priority mail shipping",
    link: "ebay-international-priority-mail-shipping-tracking",
  },
  { name: "EC Express Courier", link: "ec-express-courier-tracking" },
  {
    name: "EC First Class Courier",
    link: "ec-first-class-courier-tracking",
  },
  { name: "Ecargo Courier", link: "ecargo-courier-tracking" },
  { name: "Echo Courier", link: "echo-courier-tracking" },
  {
    name: "Ecom Express Courier ",
    link: "ecom-express-courier-tracking",
  },
  {
    name: "Economy International Courier",
    link: "economy-international-courier-tracking",
  },
  { name: "Ekart Courier ", link: "ekart-courier-tracking" },
  { name: "Elbee Courier", link: "elbee-courier-tracking" },
  { name: "Elbex Courier ", link: "elbex-courier-tracking" },
  { name: "Elta Courier", link: "elta-courier-tracking" },
  {
    name: "Elta Hellenic Post Courier",
    link: "elta-hellenic-post-courier-tracking",
  },
  {
    name: "Emirates Post Courier",
    link: "emirates-post-courier-tracking",
  },
  { name: "Emp", link: "emp-order-tracking" },
  { name: "Empost uae courier", link: "empost-uae-courier-tracking" },
  {
    name: "Emps Express Courier",
    link: "emps-express-courier-tracking",
  },
  { name: "Ensenda Courier", link: "ensenda-courier-tracking" },
  { name: "Envialia Courier", link: "envialia-courier-tracking" },
  {
    name: "Equick China Courier",
    link: "equick-china-courier-tracking",
  },
  { name: "ERS Courier", link: "ers-courier-tracking" },
  { name: "ESI Courier Courier", link: "esi-courier-courier-tracking" },
  { name: "Esquire Courier", link: "esquire-courier-tracking" },
  { name: "Estafeta Courier", link: "estafeta-courier-tracking" },
  { name: "Estes Courier", link: "estes-courier-tracking" },
  {
    name: "Eub shipping carrier",
    link: "eub-shipping-carrier-tracking",
  },
  {
    name: "Evergreen Line Container",
    link: "evergreen-line-container-tracking",
  },
  { name: "Exapaq Courier", link: "exapaq-courier-tracking" },
  { name: "Excellent Courier", link: "excellent-courier-tracking" },
  { name: "Expeditors Courier", link: "expeditors-courier-tracking" },
  { name: "Expressit Courier", link: "expressit-courier-tracking" },
  { name: "Expressit Courier ", link: "expressit-courier-tracking" },
  { name: "Eyebuydirect", link: "eyebuydirect-order-tracking" },
  { name: "Falcon Courier ", link: "falcon-courier-tracking" },
  { name: "Fanatics", link: "fanatics-order-tracking" },
  {
    name: "Fastrak Services Courier",
    link: "fastrak-services-courier-tracking",
  },
  { name: "Fedex Cross Border", link: "fedex-cross-border-tracking" },
  { name: "Fedex Freight ", link: "fedex-freight-tracking" },
  {
    name: "Fedex India Courier ",
    link: "fedex-india-courier-tracking",
  },
  { name: "Fedex UK", link: "fedex-uk-tracking" },
  { name: "Fedex US", link: "fedex-us-tracking" },
  {
    name: "Fercam Logistics Transport Courier",
    link: "fercam-logistics-transport-courier-tracking",
  },
  {
    name: "First Connection Courier",
    link: "first-connection-courier-tracking",
  },
  {
    name: "First Flight Courier",
    link: "first-flight-courier-tracking",
  },
  {
    name: "First Logistics Courier",
    link: "first-logistics-courier-tracking",
  },
  {
    name: "Flash Courier Courier",
    link: "flash-courier-courier-tracking",
  },
  {
    name: "Flash Freight Logistics Courier",
    link: "flash-freight-logistics-courier-tracking",
  },
  { name: "Flyking Courier", link: "flyking-courier-tracking" },
  {
    name: "Flyt Express Courier",
    link: "flyt-express-courier-tracking",
  },
  {
    name: "France post la poste",
    link: "france-post-la-poste-tracking",
  },
  {
    name: "Frontier communications",
    link: "frontier-communications-order-tracking",
  },
  { name: "FSC Courier", link: "fsc-courier-tracking" },
  { name: "Ftd flowers", link: "ftd-flowers-order-tracking" },
  { name: "Fto e money online", link: "fto-e-money-tracking" },
  { name: "G Somani Courier", link: "g-somani-courier-tracking" },
  {
    name: "Galaxy Express Courier",
    link: "galaxy-express-courier-tracking",
  },
  { name: "Gap", link: "gap-order-tracking" },
  { name: "Garudavega Courier", link: "garudavega-courier-tracking" },
  { name: "Gati KWE Courier ", link: "gati-kwe-courier-tracking" },
  { name: "GD Express Courier", link: "gd-express-courier-tracking" },
  { name: "GDEX Courier", link: "gdex-courier-tracking" },
  {
    name: "Geniki Taxydromiki Courier",
    link: "geniki-taxydromiki-courier-tracking",
  },
  {
    name: "Geodis Calberson France Courier",
    link: "geodis-calberson-france-courier-tracking",
  },
  { name: "Germany post", link: "germany-post-tracking" },
  { name: "Ghana post", link: "ghana-post-tracking" },
  {
    name: "Giao HàNg Nhanh Courier",
    link: "giao-hàng-nhanh-courier-tracking",
  },
  {
    name: "Globegistics Inc Courier",
    link: "globegistics-inc-courier-tracking",
  },
  {
    name: "Glodcross Cargo Courier",
    link: "glodcross-cargo-courier-tracking",
  },
  { name: "GLS Courier", link: "gls-courier-tracking" },
  { name: "GLS Czech Republic ", link: "gls-czech-republic-tracking" },
  { name: "GLS Italy Courier", link: "gls-italy-courier-tracking" },
  {
    name: "GLS Netherlands Courier",
    link: "gls-netherlands-courier-tracking",
  },
  { name: "GMS Courier", link: "gms-courier-tracking" },
  { name: "GMS Express Courier", link: "gms-express-courier-tracking" },
  { name: "GMS Worldwide", link: "gms-worldwide-tracking" },
  { name: "Go shop", link: "go-shop-order-tracking" },
  { name: "Gofly Courier", link: "gofly-courier-tracking" },
  { name: "Gojavas Courier ", link: "gojavas-courier-tracking" },
  { name: "Grand Slam Express ", link: "grand-slam-express-tracking" },
  { name: "Greenways Courier", link: "greenways-courier-tracking" },
  { name: "Greyhound Courier", link: "greyhound-courier-tracking" },
  { name: "Hari Om Courier", link: "hari-om-courier-tracking" },
  { name: "Hermes Courier", link: "hermes-courier-tracking" },
  {
    name: "Hermes Germany Courier",
    link: "hermes-germany-courier-tracking",
  },
  {
    name: "Hermes World Courier",
    link: "hermes-world-courier-tracking",
  },
  { name: "Hindustan Courier", link: "hindustan-courier-tracking" },
  {
    name: "Holland Freight Courier",
    link: "holland-freight-courier-tracking",
  },
  {
    name: "Homedirect Logistics Courier",
    link: "homedirect-logistics-courier-tracking",
  },
  {
    name: "Hong Kong Post Courier",
    link: "hong-kong-post-courier-tracking",
  },
  {
    name: "Hrvatska PošTa Courier",
    link: "hrvatska-pošta-courier-tracking",
  },
  {
    name: "Hua Han Logistics Courier",
    link: "hua-han-logistics-courier-tracking",
  },
  {
    name: "Humburgg Sud Courier",
    link: "humburgg-sud-courier-tracking",
  },
  { name: "IB Express Courier", link: "ib-express-courier-tracking" },
  { name: "Ideal Courier", link: "ideal-courier-tracking" },
  { name: "Idelivery Courier", link: "idelivery-courier-tracking" },
  { name: "IDEX Courier", link: "idex-courier-tracking" },
  { name: "IMX Mail Courier", link: "imx-mail-courier-tracking" },
  { name: "India Post ", link: "india-post-tracking" },
  {
    name: "India Post Domestic Courier",
    link: "india-post-domestic-courier-tracking",
  },
  {
    name: "India Post International Courier",
    link: "india-post-international-courier-tracking",
  },
  {
    name: "Indiaontime Courier ",
    link: "indiaontime-courier-tracking",
  },
  {
    name: "Indo Express Courier",
    link: "indo-express-courier-tracking",
  },
  { name: "Indonesia post", link: "indonesia-post-tracking" },
  {
    name: "Inpost Paczkomaty Courier",
    link: "inpost-paczkomaty-courier-tracking",
  },
  { name: "Inpost parcel", link: "inpost-parcel-tracking" },
  { name: "Interflora", link: "interflora-order-tracking" },
  {
    name: "Interlink Express Courier",
    link: "interlink-express-courier-tracking",
  },
  {
    name: "International Seur Courier",
    link: "international-seur-courier-tracking",
  },
  { name: "Iparcel Courier", link: "iparcel-courier-tracking" },
  { name: "Ips courier", link: "ips-courier-tracking" },
  { name: "Italy post", link: "italy-post-tracking" },
  { name: "IX Trans Courier", link: "ix-trans-courier-tracking" },
  { name: "J B Hunt Courier", link: "j-b-hunt-courier-tracking" },
  { name: "J crew factory", link: "j-crew-factory-order-tracking" },
  { name: "J Somani Courier", link: "j-somani-courier-tracking" },
  {
    name: "Jaipur Golden Courier",
    link: "jaipur-golden-courier-tracking",
  },
  { name: "Janco Ecommerce ", link: "janco-ecommerce-tracking" },
  { name: "Japan Post ", link: "japan-post-tracking" },
  { name: "Jcp", link: "jcp-order-tracking" },
  { name: "Jetex Courier", link: "jetex-courier-tracking" },
  { name: "Jimmy jazz", link: "jimmy-jazz-order-tracking" },
  { name: "JK Courier", link: "jk-courier-tracking" },
  {
    name: "JNE International Courier",
    link: "jne-international-courier-tracking",
  },
  { name: "JP Express Courier", link: "jp-express-courier-tracking" },
  { name: "JRS Express Courier", link: "jrs-express-courier-tracking" },
  { name: "JT Express Malaysia", link: "jt-express-malaysia-tracking" },
  {
    name: "JT Express Malaysia ",
    link: "jt-express-malaysia-tracking",
  },
  { name: "Jupiter Courier", link: "jupiter-courier-tracking" },
  { name: "Justfab", link: "justfab-order-tracking" },
  { name: "Kate spade", link: "kate-spade-order-tracking" },
  { name: "Kerry Indev Express", link: "kerry-indev-express-tracking" },
  {
    name: "Kerry Indev Express ",
    link: "kerry-indev-express-tracking",
  },
  { name: "Kesineni Courier", link: "kesineni-courier-tracking" },
  { name: "Kfc", link: "kfc-order-tracking" },
  { name: "Khubani Courier", link: "khubani-courier-tracking" },
  { name: "Kourtier Courier", link: "kourtier-courier-tracking" },
  { name: "KTM Courier", link: "ktm-courier-tracking" },
  {
    name: "KWE Kintetsu World Express Courier",
    link: "kwe-kintetsu-world-express-courier-tracking",
  },
  { name: "Kylie cosmetics", link: "kylie-cosmetics-order-tracking" },
  { name: "La Poste", link: "la-poste-tracking" },
  {
    name: "Lakeside collection",
    link: "lakeside-collection-order-tracking",
  },
  { name: "Lalji Mulji Courier", link: "lalji-mulji-courier-tracking" },
  { name: "Lamps plus", link: "lamps-plus-order-tracking" },
  { name: "Lasership Courier ", link: "lasership-courier-tracking" },
  {
    name: "Latestone online shopping",
    link: "latestone-online-shopping-order-tracking",
  },
  { name: "Laxmi Courier", link: "laxmi-courier-tracking" },
  {
    name: "LDS Delivery Courier",
    link: "lds-delivery-courier-tracking",
  },
  {
    name: "Lebanon liban post ems",
    link: "lebanon-liban-post-ems-tracking",
  },
  {
    name: "Legend Cargo Courier",
    link: "legend-cargo-courier-tracking",
  },
  { name: "Lenscrafters", link: "lenscrafters-order-tracking" },
  { name: "Leopard Courier", link: "leopard-courier-tracking" },
  { name: "Lexship Courier ", link: "lexship-courier-tracking" },
  { name: "Liberty shoes online", link: "liberty-shoes-tracking" },
  { name: "Linex Courier", link: "linex-courier-tracking" },
  { name: "Links Courier", link: "links-courier-tracking" },
  { name: "Looomis Courier", link: "looomis-courier-tracking" },
  { name: "Lycamobile online", link: "lycamobile-tracking" },
  { name: "Mac cosmetics online", link: "mac-cosmetics-tracking" },
  { name: "Madhur Courier ", link: "madhur-courier-tracking" },
  {
    name: "Magyar posta hungary post",
    link: "magyar-posta-hungary-post-tracking",
  },
  { name: "Mahabali Courier", link: "mahabali-courier-tracking" },
  {
    name: "Mail Boxes Etc Courier",
    link: "mail-boxes-etc-courier-tracking",
  },
  { name: "Mainfreight Courier", link: "mainfreight-courier-tracking" },
  {
    name: "Malaysia Post",
    link: "malaysia-post-tracking",
  },

  { name: "Malta post ems", link: "malta-post-ems-tracking" },
  { name: "Marudhar Courier", link: "marudhar-courier-tracking" },
  { name: "Maruti Courier", link: "maruti-courier-tracking" },
  {
    name: "Maruti Nandan Courier",
    link: "maruti-nandan-courier-tracking",
  },
  { name: "Matrix Courier", link: "matrix-courier-tracking" },
  { name: "Mc", link: "mc-order-tracking" },
  { name: "Megacity Courier", link: "megacity-courier-tracking" },
  {
    name: "Meghraj Express Courier",
    link: "meghraj-express-courier-tracking",
  },
  {
    name: "Metro Maruti Courier",
    link: "metro-maruti-courier-tracking",
  },
  { name: "Mexico post", link: "mexico-post-tracking" },
  { name: "Midland Courier", link: "midland-courier-tracking" },
  { name: "Mirakle Courier ", link: "mirakle-courier-tracking" },
  { name: "Misspap", link: "misspap-order-tracking" },
  { name: "MOL Courier", link: "mol-courier-tracking" },
  {
    name: "Multiple carriers global package",
    link: "multiple-carriers-global-package-tracking",
  },
  { name: "Myer", link: "myer-order-tracking" },
  { name: "National Courier", link: "national-courier-tracking" },
  { name: "Nepal Air Courier", link: "nepal-air-courier-tracking" },
  { name: "Nepal Post Courier", link: "nepal-post-courier-tracking" },
  { name: "Netflorist", link: "netflorist-order-tracking" },
  {
    name: "Netherlands post postnl",
    link: "netherlands-post-postnl-tracking",
  },
  {
    name: "Network Express Courier",
    link: "network-express-courier-tracking",
  },
  { name: "New zealand post", link: "new-zealand-post-tracking" },
  { name: "Nextsmartship ", link: "nextsmartship-tracking" },
  { name: "Nfl shop", link: "nfl-shop-order-tracking" },
  { name: "Nigeria nipost", link: "nigeria-nipost-tracking" },
  { name: "Nine Star Courier", link: "nine-star-courier-tracking" },
  { name: "Ninjavan Courier", link: "ninjavan-courier-tracking" },
  { name: "NITCO Logistics ", link: "nitco-logistics-tracking" },
  {
    name: "North Eastern NECC Courier",
    link: "north-eastern-necc-courier-tracking",
  },
  {
    name: "Nova Poshta International",
    link: "nova-poshta-international-tracking",
  },
  { name: "Nuvo EX Courier", link: "nuvo-ex-courier-tracking" },
  {
    name: "OBC On Board Courier",
    link: "obc-on-board-courier-tracking",
  },
  { name: "OCS Courier Courier", link: "ocs-courier-courier-tracking" },
  { name: "Old Dominion ", link: "old-dominion-tracking" },
  { name: "Om Courier", link: "om-courier-tracking" },
  {
    name: "Om Logistics Courier",
    link: "om-logistics-courier-tracking",
  },
  { name: "Ondot Courier ", link: "ondot-courier-tracking" },
  { name: "OOCL Cargo", link: "oocl-cargo-container-tracking" },
  {
    name: "Osm worldwide shipping",
    link: "osm-worldwide-shipping-tracking",
  },
  { name: "Other carrier", link: "other-carrier-tracking" },
  { name: "Otterbox", link: "otterbox-order-tracking" },
  { name: "Overnite Courier ", link: "overnite-courier-tracking" },
  {
    name: "Overnite Express Courier ",
    link: "overnite-express-courier-tracking",
  },
  { name: "Overseas Courier", link: "overseas-courier-tracking" },
  {
    name: "Oxford Express Courier",
    link: "oxford-express-courier-tracking",
  },
  { name: "Pacsun", link: "pacsun-order-tracking" },
  { name: "Pafex Courier", link: "pafex-courier-tracking" },
  { name: "Pafex Courier ", link: "pafex-courier-tracking" },
  { name: "Pakistan post", link: "pakistan-post-tracking" },
  {
    name: "Parcel Force Courier",
    link: "parcel-force-courier-tracking",
  },
  { name: "Parcelnet courier", link: "parcelnet-courier-tracking" },
  {
    name: "Parisi Grand Smooth Logistics Courier",
    link: "parisi-grand-smooth-logistics-courier-tracking",
  },
  {
    name: "Pashupati Cargo Courier",
    link: "pashupati-cargo-courier-tracking",
  },
  { name: "Paypal package", link: "paypal-package-tracking" },
  { name: "PCS Express Courier", link: "pcs-express-courier-tracking" },
  { name: "Pegasus Courier ", link: "pegasus-courier-tracking" },
  { name: "Philippines post", link: "philippines-post-tracking" },
  { name: "Pickrr Courier ", link: "pickrr-courier-tracking" },
  { name: "Pigeon Courier ", link: "pigeon-courier-tracking" },
  { name: "Pitney Bowes ", link: "pitney-bowes-tracking" },
  { name: "Pitney bowes parcel", link: "pitney-bowes-parcel-tracking" },
  { name: "Poland post", link: "poland-post-tracking" },
  { name: "Polar Express ", link: "polar-express-tracking" },
  { name: "Poonam Courier ", link: "poonam-courier-tracking" },
  {
    name: "Pos ekspress track and trace online",
    link: "pos-ekspress-track-and-trace-online-tracking",
  },
  { name: "Poslaju ", link: "poslaju-tracking" },
  { name: "Post NL Courier", link: "post-nl-courier-tracking" },
  { name: "Poste Italiane", link: "poste-italiane-tracking" },
  { name: "Posten sweden", link: "posten-sweden-tracking" },
  { name: "Postnord Courier", link: "postnord-courier-tracking" },
  { name: "Pottery barn online", link: "pottery-barn-tracking" },
  { name: "Prayaas Courier", link: "prayaas-courier-tracking" },
  {
    name: "Professional Courier Kuwait",
    link: "professional-courier-kuwait-tracking",
  },
  {
    name: "Professional Courier Singapore",
    link: "professional-courier-singapore-tracking",
  },
  {
    name: "Professional Courier Srilanka",
    link: "professional-courier-srilanka-tracking",
  },
  {
    name: "Professional Courier UAE",
    link: "professional-courier-uae-tracking",
  },
  {
    name: "Professional Courier USA",
    link: "professional-courier-usa-tracking",
  },
  {
    name: "Procure Logistics",
    link: "procure-logistics-tracking",
  },
  { name: "Purolator Courier", link: "purolator-courier-tracking" },
  { name: "Pushpak Courier ", link: "pushpak-courier-tracking" },
  { name: "Q post qatar parcel", link: "q-post-qatar-parcel-tracking" },
  { name: "Quantium Courier ", link: "quantium-courier-tracking" },
  { name: "Rapid Delivery ", link: "rapid-delivery-tracking" },
  {
    name: "Rapidconnect Courier",
    link: "rapidconnect-courier-tracking",
  },
  { name: "Red Express", link: "red-express-tracking" },
  { name: "Redbubble", link: "redbubble-order-tracking" },
  { name: "Regent Courier", link: "regent-courier-tracking" },
  { name: "Registered Post ", link: "registered-post-tracking" },
  {
    name: "Restoration hardware",
    link: "restoration-hardware-order-tracking",
  },
  { name: "Rivigo Courier", link: "rivigo-courier-tracking" },
  { name: "RL Carriers ", link: "rl-carriers-tracking" },
  {
    name: "Road Runners Courier",
    link: "road-runners-courier-tracking",
  },
  {
    name: "Royal International Courier",
    link: "royal-international-courier-tracking",
  },
  { name: "RPX Courier", link: "rpx-courier-tracking" },
  { name: "Safexpress Courier ", link: "safexpress-courier-tracking" },
  { name: "Safexpress India", link: "safexpress-india-tracking" },
  { name: "Safmarine Courier", link: "safmarine-courier-tracking" },
  { name: "Sagawa Courier", link: "sagawa-courier-tracking" },
  { name: "Saia Courier ", link: "saia-courier-tracking" },
  {
    name: "Sailpost italy courier",
    link: "sailpost-italy-courier-tracking",
  },
  { name: "Sameday Courier ", link: "sameday-courier-tracking" },
  { name: "Saudi Post Courier", link: "saudi-post-courier-tracking" },
  { name: "Scentsy", link: "scentsy-order-tracking" },
  {
    name: "Scrubs and beyond online",
    link: "scrubs-and-beyond-tracking",
  },
  {
    name: "Scudex Express Courier",
    link: "scudex-express-courier-tracking",
  },
  { name: "SDA Express Courier", link: "sda-express-courier-tracking" },
  {
    name: "Seino transportation",
    link: "seino-transportation-tracking",
  },
  { name: "SF Express Courier", link: "sf-express-courier-tracking" },
  { name: "Shadowfax Courier ", link: "shadowfax-courier-tracking" },
  {
    name: "Shipdelight Courier ",
    link: "shipdelight-courier-tracking",
  },
  { name: "Shiprocket Courier", link: "shiprocket-courier-tracking" },
  { name: "Shiprocket Courier ", link: "shiprocket-courier-tracking" },
  { name: "Shoebuy", link: "shoebuy-order-tracking" },
  {
    name: "Shree Balaji Courier",
    link: "shree-balaji-courier-tracking",
  },
  {
    name: "Shree Mahavir Courier",
    link: "shree-mahavir-courier-tracking",
  },
  {
    name: "Shree Maruti Courier ",
    link: "shree-maruti-courier-tracking",
  },
  {
    name: "Shree Nandan Courier",
    link: "shree-nandan-courier-tracking",
  },
  {
    name: "Shree Tirupati Courier ",
    link: "shree-tirupati-courier-tracking",
  },
  { name: "Sigma Courier", link: "sigma-courier-tracking" },
  {
    name: "Silver sprint courier",
    link: "silver-sprint-courier-tracking",
  },
  {
    name: "Singapore Post Courier",
    link: "singapore-post-courier-tracking",
  },
  {
    name: "Singpost registered mail",
    link: "singpost-registered-mail-tracking",
  },
  { name: "Skyman Courier ", link: "skyman-courier-tracking" },
  { name: "Skynet Australia ", link: "skynet-australia-tracking" },
  { name: "Skynet Germany ", link: "skynet-germany-tracking" },
  { name: "Skynet India ", link: "skynet-india-tracking" },
  { name: "Skynet Malaysia ", link: "skynet-malaysia-tracking" },
  { name: "Skynet Mexico ", link: "skynet-mexico-tracking" },
  { name: "Skynet Nigeria ", link: "skynet-nigeria-tracking" },
  { name: "Skynet Pakistan ", link: "skynet-pakistan-tracking" },
  { name: "Skynet Philippines ", link: "skynet-philippines-tracking" },
  { name: "Skynet Singapore ", link: "skynet-singapore-tracking" },
  { name: "Skynet UAE ", link: "skynet-uae-tracking" },
  { name: "Skynet USA", link: "skynet-usa-tracking" },
  {
    name: "Skynet Worldwide Express",
    link: "skynet-worldwide-express-tracking",
  },
  { name: "Skynet Yemen", link: "skynet-yemen-tracking" },
  { name: "SMSA Express ", link: "smsa-express-tracking" },
  { name: "Soccer com", link: "soccer-com-order-tracking" },
  {
    name: "South African Post Courier",
    link: "south-african-post-courier-tracking",
  },
  { name: "Spain post", link: "spain-post-tracking" },
  {
    name: "Speed & Safe Courier",
    link: "speed-&-safe-courier-tracking",
  },
  { name: "Speed Post ", link: "speed-post-tracking" },
  { name: "Speedex Courier", link: "speedex-courier-tracking" },
  {
    name: "Speedypost LLP Courier",
    link: "speedypost-llp-courier-tracking",
  },
  {
    name: "Sportsmans guide online",
    link: "sportsmans-guide-tracking",
  },
  { name: "Spoton Courier", link: "spoton-courier-tracking" },
  { name: "Star Track Courier", link: "star-track-courier-tracking" },
  { name: "Store Viva Courier", link: "store-viva-courier-tracking" },
  {
    name: "Sweden post postnord",
    link: "sweden-post-postnord-tracking",
  },
  { name: "Swiss Post ", link: "swiss-post-tracking" },
  { name: "Taiwan post", link: "taiwan-post-tracking" },
  { name: "Target Courier ", link: "target-courier-tracking" },
  { name: "Taxipost", link: "taxipost-tracking" },
  { name: "TCI Express Courier", link: "tci-express-courier-tracking" },
  { name: "TCI Freight Courier", link: "tci-freight-courier-tracking" },
  { name: "TCI Xps Courier", link: "tci-xps-courier-tracking" },
  { name: "TCS Courier", link: "tcs-courier-tracking" },
  { name: "Teepublic", link: "teepublic-order-tracking" },
  { name: "Tej Courier", link: "tej-courier-tracking" },
  { name: "Tele2 online", link: "tele2-tracking" },
  {
    name: "Thailand Post Courier",
    link: "thailand-post-courier-tracking",
  },
  { name: "Tirupati Courier", link: "tirupati-courier-tracking" },
  { name: "TNT Courier ", link: "tnt-courier-tracking" },
  { name: "TNT Reference", link: "tnt-reference-tracking" },
  { name: "TNT UK", link: "tnt-uk-tracking" },
  { name: "Toll Group Courier", link: "toll-group-courier-tracking" },
  { name: "Trackon Courier ", link: "trackon-courier-tracking" },
  { name: "Trackr", link: "trackr-order-tracking" },
  { name: "UBX Courier", link: "ubx-courier-tracking" },
  { name: "UK Mail Courier", link: "uk-mail-courier-tracking" },
  { name: "United Courier ", link: "united-courier-tracking" },
  {
    name: "United Sajha Courier",
    link: "united-sajha-courier-tracking",
  },
  { name: "Usc", link: "usc-order-tracking" },
  { name: "V Express Courier", link: "v-express-courier-tracking" },
  { name: "V Trans Courier", link: "v-trans-courier-tracking" },
  { name: "V-Xpress Courier", link: "v-xpress-courier-tracking" },
  { name: "Vichare Courier ", link: "vichare-courier-tracking" },
  {
    name: "Vision International Cargo Courier",
    link: "vision-international-cargo-courier-tracking",
  },
  { name: "Vrl Courier", link: "vrl-courier-tracking" },
  {
    name: "Vrl Logistics Courier",
    link: "vrl-logistics-courier-tracking",
  },
  { name: "Vtrans Courier ", link: "vtrans-courier-tracking" },
  { name: "Vulcan Courier ", link: "vulcan-courier-tracking" },
  { name: "Wet seal", link: "wet-seal-order-tracking" },
  { name: "Winit Courier ", link: "winit-courier-tracking" },
  {
    name: "Wow Express Courier ",
    link: "wow-express-courier-tracking",
  },
  { name: "XDEL Courier", link: "xdel-courier-tracking" },
  { name: "Xpressbees Courier ", link: "xpressbees-courier-tracking" },
  { name: "XPS Courier", link: "xps-courier-tracking" },
  { name: "Yamato Japan ", link: "yamato-japan-tracking" },
  { name: "Yang Ming Courier", link: "yang-ming-courier-tracking" },
  { name: "Yodel Courier", link: "yodel-courier-tracking" },
  { name: "Younique", link: "younique-order-tracking" },
  { name: "YRC Freight Courier", link: "yrc-freight-courier-tracking" },
  { name: "Yun Express ", link: "yun-express-tracking" },
  { name: "ZTO Express", link: "zto-express-tracking" },

  {
    name: "Loadshare Networks",
    link: "loadshare-networks-tracking",
    url: "https://www.loadshare.net/",
  },
  {
    name: "Zim Line Container",
    link: "zim-line-container-tracking",
    url: "https://www.zim.com/",
  },
  {
    name: "Mark Express",
    link: "mark-express-courier-tracking",
    url: "https://markexpress.co.in/",
  },
  {
    name: "Transworld Container",
    link: "transworld-container-tracking",
    url: "https://transworld-terminals.com/index.html",
  },
  {
    name: "Zapvi",
    link: "zapvi-order-tracking",
    url: "https://zapvi.in/",
  },
  {
    name: "Flipkart",
    link: "flipkart-order-tracking",
    url: "https://www.flipkart.com/",
  },
  {
    name: "Goldstar Line Container",
    link: "goldstar-line-container-tracking",
    url: "https://www.goldstarline.com/#/India",
  },
  {
    name: "LBC Express Shipping",
    link: "lbc-express-shipping-tracking",
    url: "https://www.lbcexpress.com/",
  },
  {
    name: "MSC Cargo Container",
    link: "msc-cargo-container-tracking",
    url: "https://www.msc.com/",
  },
  {
    name: "Yanwen Logistics",
    link: "yanwen-logistics-tracking",
    url: "https://www.yw56.com.cn/en/",
  },
  {
    name: "Purolator Canada",
    link: "purolator-canada-tracking",
    url: "https://www.purolator.com/en",
  },
  {
    name: "Great India Roadways",
    link: "great-india-roadways-tracking",
    url: "https://greatindia.net.in/",
  },
  {
    name: "XPO Logistics",
    link: "xpo-logistics-transport-tracking",
    url: "https://www.xpo.com/",
  },
  {
    name: "Hapag LLoyd",
    link: "hapag-lloyd-container-tracking",
    url: "https://www.hapag-lloyd.com/en/home.html",
  },
  {
    name: "Air Canada Cargo",
    link: "air-canada-cargo-tracking",
    url: "https://www.aircanada.com/cargo/",
  },
  {
    name: "Thai Airways Cargo",
    link: "thai-airways-cargo-tracking",
    url: "https://www.thaicargo.com/en/main",
  },
  {
    name: "Air France Cargo",
    link: "air-france-cargo-tracking",
    url: "https://www.afklcargo.com/IN/en/local/homepage/homepage.jsp",
  },
  {
    name: "Bhavna Roadways Transport",
    link: "bhavna-roadways-transport-tracking",
    url: "https://bhavnaroadways.com/index.php",
  },
  {
    name: "Qatar Airways Cargo",
    link: "qatar-airways-cargo-tracking",
    url: "https://www.qrcargo.com/s/",
  },
  {
    name: "RCL",
    link: "rcl-container-tracking",
    url: "https://www.rclgroup.com/Default.aspx",
  },
  {
    name: "HMM",
    link: "hmm-container-tracking",
    url: "https://www.hmm21.com/company.do",
  },
  {
    name: "Indigo Air Cargo",
    link: "indigo-air-cargo-tracking",
    url: "https://6ecargo.goindigo.in/",
  },
  {
    name: "International Express Courier ",
    link: "international-express-courier-tracking",
    url: "http://www.internationalexp.com/Default.aspx",
  },
  {
    name: "Canada Post",
    link: "canada-post-office-tracking",
    url: "https://www.canadapost-postescanada.ca/cpc/en?name=tgt",
  },
  {
    name: "Yun Express",
    link: "yun-express-tracking",
    url: "https://www.yunexpress.com/",
  },
  {
    name: "DPD International",
    link: "dpd-international-courier-tracking",
    url: "https://www.dpd.com/nl/en/",
  },
  {
    name: "Yodel UK",
    link: "yodel-tracking-uk",
    url: "https://www.yodel.co.uk/",
  },
  {
    name: "SMSA Express",
    link: "smsa-express-courier-tracking",
    url: "https://www.smsaexpress.com/",
  },
  {
    name: "CEVA Logistics",
    link: "ceva-logistics-tracking",
    url: "https://www.cevalogistics.com/en",
  },
  {
    name: "Evergreen Line Container",
    link: "evergreen-line-container-tracking",
    url: "https://www.evergreen-marine.com/emc/",
  },
  {
    name: "ABF Freight",
    link: "abf-freight-tracking",
    url: "https://arcb.com/",
  },
  {
    name: "YRC Freight",
    link: "yrc-freight-tracking",
    url: "https://yrc.com/",
  },
  {
    name: "UPS Courier India",
    link: "ups-courier-tracking-india",
    url: "https://www.ups.com/in/en/Home.page",
  },
  {
    name: "Skynet Worldwide Express",
    link: "skynet-worldwide-express-tracking",
    url: "https://www.skynet.net/india",
  },
  {
    name: "OOCL Cargo Container",
    link: "oocl-cargo-container-tracking",
    url: "https://www.oocl.com/india/eng/Pages/default.aspx",
  },
  {
    name: "TCS Courier",
    link: "tcs-courier-tracking",
    url: "https://www.tcsexpress.com/",
  },
  {
    name: "Spicejet Cargo",
    link: "spicejet-cargo-tracking",
    url: "https://www.spicexpress.com/",
  },
  {
    name: "Finnair Cargo",
    link: "finnair-cargo-tracking",
    url: "https://cargo.finnair.com/en",
  },
  {
    name: "ICEGATE Air IGM",
    link: "icegate-air-igm-tracking",
    url: "https://enquiry.icegate.gov.in/enquiryatices/airIgmEntry",
  },
  {
    name: "Fastway Worldwide Express",
    link: "fastway-worldwide-express-tracking",
    url: "https://fastwayindia.com/",
  },
  {
    name: "Sinokor",
    link: "sinokor-tracking",
    url: "http://www.sinokor.co.kr/en/index.html",
  },
  {
    name: "ATS Courier",
    link: "ats-courier-tracking",
    url: "https://atscargo.in/index.aspx",
  },
  {
    name: "Wan Hai Container",
    link: "wan-hai-container-tracking",
    url: "https://www.wanhai.com/views/Main.xhtml",
  },
  {
    name: "Yang Ming Container",
    link: "yang-ming-container-tracking",
    url: "https://www.yangming.com/index.aspx",
  },
  {
    name: "Pon Pure Logistics",
    link: "pon-pure-logistics-tracking",
    url: "https://www.ponpurelogistics.com/home",
  },
  {
    name: "Vamaship",
    link: "vamaship-tracking",
    url: "https://www.vamaship.com/",
  },
  {
    name: "Shipping Corporation of India",
    link: "shipping-corporation-of-india-tracking",
    url: "https://www.shipindia.com/",
  },
  {
    name: "Ritco Logistics",
    link: "ritco-logistics-tracking",
    url: "https://www.rajdhaniinterstate.com/",
  },
  {
    name: "XFAS",
    link: "xfas-tracking",
    url: "https://www.xfas.in/index.php",
  },
  {
    name: "Shipco Transport",
    link: "shipco-transport-tracking",
    url: "https://www.shipco.com/",
  },
  {
    name: "Stun Sign Logistics",
    link: "stun-sign-logistics-tracking",
    url: "https://www.sskerala.com/",
  },
  {
    name: "Online Express Courier",
    link: "online-express-courier-tracking",
    url: "https://onlinexpress.co.in/",
  },
  {
    name: "Seabreeze Cargo",
    link: "seabreeze-cargo-tracking",
    url: "https://www.seabreezecouriers.com/",
  },
  {
    name: "MML Express Courier",
    link: "mml-express-courier-tracking",
    url: "http://mmlexpress.com/index.php",
  },
  {
    name: "TAC Logistics",
    link: "tac-logistics-tracking",
    url: "http://taclogistics.in/index.html",
  },
  {
    name: "Mudita Transport Courier",
    link: "mudita-transport-courier-tracking",
    url: "https://www.muditacargo.com/index.php",
  },
  {
    name: "OxyZen Logistics",
    link: "oxyzen-logistics-tracking",
    url: "https://www.oxyzenexpress.com/#/",
  },
  {
    name: "Navkar CFS Container",
    link: "navkar-cfs-container-tracking",
    url: "https://www.navkarcfs.com/a/index.php",
  },
  {
    name: "Parveen Express",
    link: "parveen-express-tracking",
    url: "http://www.parveenexpress.com/",
  },
  {
    name: "Falcon",
    link: "falcon-courier-tracking",
    url: "http://falconcourier.net/index.html",
  },
  {
    name: "Ship Global",
    link: "ship-global-tracking",
    url: "https://shipglobal.in/",
  },
  {
    name: "Kabra Express Logistics",
    link: "kabra-express-logistics-tracking",
    url: "http://www.kabraexpress.in/index.html",
  },
  {
    name: "MPCL Courier",
    link: "mpcl-courier-tracking",
    url: "http://www.maxlogistic.com:8888/Maxlogistic/index.htm",
  },
  {
    name: "Mehta Transport",
    link: "mehta-transport-tracking",
    url: "https://mehtatransportcorporations.com/",
  },
  {
    name: "APEX",
    link: "apex-tracking",
    url: "http://www.apexcourier.in/index.php",
  },
  {
    name: "EFC Logistics Container",
    link: "efc-logistics-container-tracking",
    url: "https://efclogistics.com/index.html",
  },
  {
    name: "DR Courier Cargo",
    link: "dr-courier-cargo-tracking",
    url: "https://www.drcourierexp.com/",
  },
  {
    name: "Blowhorn",
    link: "blowhorn-tracking",
    url: "https://blowhorn.com/",
  },
  {
    name: "Primex Logistics",
    link: "primex-logistics-tracking",
    url: "http://www.primexglobal.in/",
  },
  {
    name: "Corporate Courier",
    link: "corporate-courier-tracking",
    url: "http://www.corporatecourier.in/index.html",
  },
  {
    name: "Orient Express",
    link: "orient-express-tracking",
    url: "http://www.orientexpindia.com/index.php",
  },
  {
    name: "BNL Air Service Courier",
    link: "bnl-air-service-courier-tracking",
    url: "http://bnlair.in/index.html",
  },
  {
    name: "TCCS",
    link: "tccs-tracking",
    url: "http://www.tccs.in/",
  },
  {
    name: "ACE Express Courier",
    link: "ace-courier-tracking",
    url: "https://www.aceexpressindia.com/index.html",
  },
  {
    name: "Bombax Courier",
    link: "bombax-courier-tracking",
    url: "https://bombax.in/",
  },
  {
    name: "Quick Courier Logistics",
    link: "quick-courier-logistics-tracking",
    url: "https://quickcl.com/index.php",
  },
  {
    name: "TSRTC Cargo",
    link: "tsrtc-cargo-tracking",
    url: "https://www.tsrtcparcel.in/",
  },
  {
    name: "GMR Cargo",
    link: "gmr-cargo-tracking",
    url: "https://gmrhydcargo.in/",
  },
  {
    name: "Aramex Courier",
    link: "aramex-courier-tracking",
    url: "https://www.aramex.com/in/en/home",
  },
  {
    name: "Quick Mail Solutions",
    link: "quick-mail-solutions-tracking",
    url: "https://www.qmscourier.com/",
  },
  {
    name: "SNGT",
    link: "sngt-tracking",
    url: "https://sngtgroup.com/",
  },
  {
    name: "Prime Express",
    link: "prime-express-tracking",
    url: "http://www.primecrc.com/index.aspx",
  },
  {
    name: "Shree Balaji Courier",
    link: "shree-balaji-courier-tracking",
    url: "https://balajicourier.com/",
  },
  {
    name: "Shipyaari Courier",
    link: "shipyaari-tracking",
    url: "https://www.shipyaari.com/",
  },
  {
    name: "CCF Logistics",
    link: "ccf-logistics-tracking",
    url: "http://www.ccflogistic.com/",
  },
  {
    name: "Air Vistara Cargo",
    link: "air-vistara-cargo-tracking",
    url: "https://www.airvistara.com/",
  },
  {
    name: "B4 Logistics",
    link: "b4-logistics-tracking",
    url: "https://b4logistic.com/",
  },
  {
    name: "VRL Tracking",
    link: "vrl-tracking",
    url: "https://www.vrlgroup.in/",
  },
  {
    name: "LDB Container",
    link: "ldb-container-tracking",
    url: "https://www.ldb.co.in/ldb/containersearch",
  },
  {
    name: "Shree Azad Transport",
    link: "shree-azad-transport-tracking",
    url: "http://www.shreeazad.com/",
  },
  {
    name: "ARC",
    link: "associated-road-carriers-limited-tracking",
    url: "https://www.arclimited.com/",
  },
  {
    name: "Arihant Courier",
    link: "arihant-courier-tracking",
    url: "https://www.arihantcourier.com/",
  },
  {
    name: "V3",
    link: "v3-tracking",
    url: "https://www.v3expresscargo.com/",
  },
  {
    name: "Meghraj Express Courier",
    link: "meghraj-express-courier-tracking",
    url: "http://meghraj.co.in/",
  },
  {
    name: "ACMES Tracking",
    link: "acmes-tracking",
    url: "https://www.acmes.in/Live/index.aspx",
  },
  {
    name: "PCCS Tracking",
    link: "pccs-tracking",
    url: "http://www.pccscargo.com/index.aspx",
  },
  {
    name: "DPGC Transport",
    link: "dpgc-tracking",
    url: "http://www.dpgconline.com/index.php",
  },
  {
    name: "Shiprocket",
    link: "shiprocket-tracking",
    url: "https://www.shiprocket.in/",
  },
  {
    name: "CMA CGM Tracking",
    link: "cma-cgm-tracking",
    url: "https://www.cma-cgm.com/",
  },
  {
    name: "NBET Courier",
    link: "nbet-tracking",
    url: "https://www.nbet.in/Default.aspx",
  },
  {
    name: "AR Logistics Courier",
    link: "ar-logistics-tracking",
    url: "https://arlogistics.in/index.html",
  },
  {
    name: "FedEx Freight",
    link: "fedex-tracking",
    url: "https://www.fedex.com/en-in/home.html",
  },
  {
    name: "Omni Tracking",
    link: "omni-tracking",
    url: "https://omniexpress.in/",
  },
  {
    name: "HP Order",
    link: "hp-order-tracking",
    url: "https://hpcourier.com/",
  },
  {
    name: "Nimbuspost Courier",
    link: "nimbuspost-courier-tracking",
    url: "https://nimbuspost.com/",
  },
  {
    name: "Udaan Express Courier",
    link: "udaan-express-courier-tracking",
    url: "https://udaanexpress.com/",
  },
  {
    name: "CriticaLog Tracking",
    link: "criticalog-tracking",
    url: "https://criticalog.com/",
  },
  {
    name: "Pickdel Express",
    link: "pickdel-tracking",
    url: "https://pickdel.in/",
  },
  {
    name: "Palande Courier",
    link: "palande-courier-tracking",
    url: "https://palandecourier.com/track.html",
  },
  {
    name: "Ghatge Patil Transport",
    link: "ghatge-patil-transport-tracking",
    url: "https://www.ghatgepatiltransport.com/",
  },
  {
    name: "Airways Courier",
    link: "airways-courier-tracking",
    url: "https://airwayscourier.co.in/",
  },
  {
    name: "Kerry Indev Express",
    link: "kerry-indev-express-tracking",
    url: "https://kerryindevexpress.com/",
  },
  {
    name: "K D Courier",
    link: "k-d-courier-tracking",
    url: "https://kdcourier.com/",
  },
  {
    name: "Speed and Safe Courier",
    link: "speed-and-safe-courier-tracking",
    url: "https://www.gokulamspeedandsafe.com/",
  },
  {
    name: "GDL Container",
    link: "gdl-courier-tracking",
    url: "https://www.gatewaydistriparks.com/",
  },
  {
    name: "Navata Transport",
    link: "navata-transport-tracking",
    url: "https://www.navata.com/",
  },
  {
    name: "DRTC Transport",
    link: "drtc-tracking",
    url: "https://www.drtctracking.com/",
  },
  {
    name: "Saurashtra Roadways Bangalore",
    link: "saurashtra-roadways-bangalore-tracking",
    url: "https://srb.co.in/",
  },
  {
    name: "Sahara Courier Tracking",
    link: "sahara-courier-tracking",
    url: "https://www.saharaexpress.com/",
  },
  {
    name: "Kranthi Transport",
    link: "kranthi-transport-tracking",
    url: "https://www.krantiroadtransport.com/",
  },
  {
    name: "Bullet Logistics",
    link: "bullet-logistics-tracking",
    url: "https://bulletlogistics.in/",
  },
  {
    name: "Inland World Logistics",
    link: "inland-world-logistics-tracking",
    url: "https://www.inlandworldlogistics.com/",
  },
  {
    name: "Sugam Parivahan",
    link: "sugam-parivahan-tracking",
    url: "https://www.sugamgroup.com/",
  },
  {
    name: "ICL Tracking",
    link: "icl-tracking",
    url: "http://www.iclexpress.in/",
  },
  {
    name: "APS Tracking",
    link: "aps-tracking",
    url: "http://www.apscargo.com/",
  },
  {
    name: "ABT Parcel Services",
    link: "abt-parcel-services-tracking",
    url: "http://abtps.com/",
  },
  {
    name: "Madhur Courier",
    link: "madhur-courier-service",
    url: "https://www.madhurcouriers.in/",
  },
  {
    name: "HTPL Tracking",
    link: "htpl-tracking",
    url: "https://www.hindterminals.com/",
  },
  {
    name: "Secure Tracking",
    link: "secure-tracking",
    url: "https://secureexp.com/",
  },
  {
    name: "SRD Tracking",
    link: "srd-tracking",
    url: "https://srdlogistics.com/",
  },
  {
    name: "Merchant Courier",
    link: "merchant-courier-tracking",
    url: "http://www.merchantscourier.in/",
  },
  {
    name: "Pavan Courier",
    link: "pavan-courier-tracking",
    url: "http://pavancourierservice.com/",
  },
  {
    name: "Globelink",
    link: "globelink-tracking",
    url: "http://www.globelinkww.com/",
  },
  {
    name: "SM Tracking",
    link: "sm-tracking",
    url: "http://smexpresslogistics.com/",
  },
  {
    name: "Countrywide Logistics",
    link: "countrywide-logistics-tracking",
    url: "http://www.countrywidelogistics.co.in/",
  },
  {
    name: "Rathimeena Parcel",
    link: "rathimeena-parcel-service-tracking",
    url: "https://www.rathimeenaspeedparcel.com/",
  },
  {
    name: "Garudavega",
    link: "garudavega-tracking",
    url: "https://www.garudavega.com/",
  },
  {
    name: "Transit Point Logistics",
    link: "tpl-tracking",
    url: "http://www.transitpl.com/",
  },
  {
    name: "BMPS Tracking",
    link: "bmps-tracking",
    url: "http://www.bmps.co.in/",
  },
  {
    name: "SRMT Tracking",
    link: "srmt-tracking",
    url: "https://srmt.com/",
  },
  {
    name: "KRS Tracking",
    link: "krs-tracking",
    url: "http://www.krs.co.in/",
  },
  {
    name: "BSA Logistics",
    link: "bsa-logistics-tracking",
    url: "http://www.bsa.co.in/",
  },
  {
    name: "Econship",
    link: "econship-tracking",
    url: "https://erp.econshipping.com/#/",
  },
  {
    name: "EPSPL Tracking",
    link: "epspl-tracking",
    url: "https://epspl.co.in/",
  },
  {
    name: "EPS Tracking",
    link: "eps-tracking",
    url: "https://epsworldwide.co.in/",
  },
  {
    name: "Expert Tracking",
    link: "expert-courier-tracking",
    url: "https://www.expertcourier.co.in/",
  },
  {
    name: "Jetline Courier",
    link: "jetline-courier-tracking",
    url: "https://www.jetlinecouriers.in/",
  },
  {
    name: "Team Global",
    link: "team-global-tracking",
    url: "https://www.teamglobal.in/",
  },
  {
    name: "Pushpak Courier",
    link: "pushpak-courier-tracking",
    url: "https://www.pushpakcourier.net/",
  },
  {
    name: "Simply Tracking",
    link: "simply-tracking",
    url: "https://www.simplylogistics.in/",
  },
  {
    name: "Mass Tracking",
    link: "mass-tracking",
    url: "https://meccargo.com/",
  },
  {
    name: "Onpoint Express Courier",
    link: "onpoint-tracking",
    url: "https://onpoint.in/",
  },
  {
    name: "Airstar Express",
    link: "airstar-courier-tracking",
    url: "https://airstarxpress.com/",
  },
  {
    name: "V-Xpress",
    link: "v-xpress-tracking",
    url: "https://www.vxpress.in/",
  },
  {
    name: "V-Trans Tracking",
    link: "v-trans-tracking-india",
    url: "https://vtransgroup.com/",
  },
  {
    name: "TCI Express",
    link: "tci-express-tracking",
    url: "https://www.tciexpress.in/",
  },
  {
    name: "DP World Container",
    link: "dp-world-container-tracking",
    url: "https://www.dpworld.com/india",
  },
  {
    name: "Franch Express",
    link: "franch-express-courier-tracking",
    url: "http://www.franchexpress.com/",
  },
  {
    name: "Bombino Tracking",
    link: "bombino-tracking",
    url: "https://www.bombinoexp.com/en-in/tracking",
  },
  {
    name: "KPN Parcel Service",
    link: "kpn-parcel-service-tracking",
    url: "https://www.kpnparcel.in/",
  },
  {
    name: "Shree Nandan Courier",
    link: "shree-nandan-courier-tracking",
    url: "http://www.shreenandancourier.com/",
  },
  {
    name: "Smartr Logistics",
    link: "smartr-logistics-tracking",
    url: "https://smartr.in/",
  },
  {
    name: "Maruti Air Courier",
    link: "maruti-air-courier-tracking",
    url: "https://www.marutiair.com/",
  },
  {
    name: "Overseas Tracking",
    link: "overseas-tracking",
    url: "http://www.overseaslogistics.in/",
  },
  {
    name: "Mettur Transport",
    link: "mettur-transport-tracking",
    url: "https://www.metturtransports.com/",
  },
  {
    name: "GMS Courier",
    link: "gms-courier-tracking",
    url: "https://gmsworldwide.com/",
  },
  {
    name: "ACPL Tracking",
    link: "acpl-tracking",
    url: "https://acplcargo.com/",
  },
  {
    name: "Nitco Tracking",
    link: "nitco-tracking",
    url: "https://www.nitcologistics.com/",
  },
  {
    name: "Jaipur Golden",
    link: "jaipur-golden-tracking",
    url: "https://jaipurgolden.in/",
  },
  {
    name: "ECSSPL Tracking",
    link: "ecsspl-tracking",
    url: "http://www.ecsspl.com/",
  },
  {
    name: "Akash Ganga Courier",
    link: "akash-ganga-courier-tracking",
    url: "http://www.akashganga.info/",
  },
  {
    name: "RCPL Tracking",
    link: "rcpl-tracking",
    url: "http://www.rcpl.net.in/",
  },
  {
    name: "Scorpion Tracking",
    link: "scorpion-tracking",
    url: "https://scorpiongroup.in/",
  },
  {
    name: "Lalji Mulji",
    link: "lalji-mulji-transport-tracking",
    url: "https://lmtco.com/",
  },
  {
    name: "World First Courier",
    link: "world-first-courier-tracking",
    url: "https://worldfirst.in/",
  },
  {
    name: "Arco Transport Transport",
    link: "arco-transport-tracking",
    url: "https://www.arcoroadways.com/",
  },
  {
    name: "Surat Ahmedabad Transport",
    link: "surat-ahmedabad-transport-tracking",
    url: "http://www.suratahmedabadtransport.com/",
  },
  {
    name: "Pionexxco Tracking",
    link: "pionexxco-tracking",
    url: "http://www.pionexxco.net/",
  },
  {
    name: "ATC Tracking",
    link: "atc-tracking",
    url: "https://atcls.net/",
  },
  {
    name: "Vichare Courier",
    link: "vichare-courier-tracking",
    url: "https://vichare.com/",
  },
  {
    name: "Atlantic Courier",
    link: "atlantic-courier-tracking",
    url: "https://atlanticcourier.net/",
  },
  {
    name: "Avikam Tracking",
    link: "avikam-tracking",
    url: "http://avikamindia.com/",
  },
  {
    name: "iThink Logistics",
    link: "ithink-logistics-courier-tracking",
    url: "https://www.ithinklogistics.com/",
  },
  {
    name: "Sequel Courier",
    link: "sequel-courier-tracking",
    url: "https://sequelglobal.com/",
  },
  {
    name: "The Professional Courier",
    link: "the-professional-courier-tracking",
    url: "https://www.tpcindia.com/",
  },
  {
    name: "OnDot Courier",
    link: "ondot-courier-tracking",
    url: "http://ondotcouriers.co.in/",
  },
  {
    name: "ICC Worldwide Courier",
    link: "icc-worldwide-courier-tracking",
    url: "http://iccworld.com/",
  },
  {
    name: "United Express Courier",
    link: "united-express-courier-tracking",
    url: "https://unitedexpress.in/",
  },
  {
    name: "Reliance Courier",
    link: "reliance-courier-tracking",
    url: "http://www.reliancecourier.in/",
  },
  {
    name: "Rivigo Courier",
    link: "rivigo-courier-tracking",
    url: "https://www.rivigo.com/",
  },
  {
    name: "Xspeed Logistics",
    link: "xpeed-logistics-tracking",
    url: "https://www.xpeed.in/",
  },
  {
    name: "AKR Express Parcel",
    link: "akr-tracking",
    url: "https://akrexpress.com/",
  },
  {
    name: "Mata Transport",
    link: "mata-transport-tracking",
    url: "https://matatransport.com/",
  },
  {
    name: "Global India Express",
    link: "global-india-express-tracking",
    url: "https://www.globalindiaexpress.com/",
  },
  {
    name: "Goodluck Courier",
    link: "goodluck-courier-tracking",
    url: "https://www.goodluckcourier.com/",
  },
  {
    name: "Orange Cargo Carriers",
    link: "orange-cargo-carriers-tracking",
    url: "http://www.orangecargo.in/",
  },
  {
    name: "Oxford Express",
    link: "oxford-express-courier-tracking",
    url: "http://oxfordexp.com/",
  },
  {
    name: "Safexpress",
    link: "safexpress-tracking",
    url: "http://www.safexpress.com/",
  },
  {
    name: "ST Courier",
    link: "st-courier-tracking",
    url: "http://stcourier.com/",
  },
  {
    name: "Shree Anjani Courier",
    link: "shree-anjani-courier-tracking",
    url: "http://shreeanjanicourier.com/",
  },
  {
    name: "Shree Mahavir",
    link: "shree-mahavir-courier-tracking",
    url: "http://shreemahavircourier.com/",
  },
  {
    name: "AWCC Courier",
    link: "awcc-courier-tracking",
    url: "https://www.awcc.in/",
  },
  {
    name: "Kalayatan Cargo",
    link: "kalayatan-cargo-tracking",
    url: "https://kalayatancargo.com/",
  },
  {
    name: "Exzone Logistics",
    link: "exzone-logistics-tracking",
    url: "http://www.exzone.in/",
  },
  {
    name: "Yes Courier",
    link: "yes-courier-tracking",
    url: "http://www.yescourier.in/",
  },
  {
    name: "Jaydeep Logistics",
    link: "jaydeep-logistics-tracking",
    url: "https://jaydeeplogistic.com/",
  },
  {
    name: "Skyman Air Express",
    link: "skyman-air-express-courier-tracking",
    url: "http://skymanairexpress.com/",
  },
  {
    name: "Haulage Logistics",
    link: "haulage-logistics-tracking",
    url: "https://haulagelogistics.in/",
  },
  {
    name: "Som Logistics Solution",
    link: "som-logistics-tracking",
    url: "https://www.slsindia.co.in/",
  },
  {
    name: "Kesari Courier",
    link: "kesari-courier-tracking",
    url: "https://www.kesaricourier.com/",
  },
  {
    name: "Gati Courier",
    link: "gati-courier-tracking",
    url: "https://www.gati.com/",
  },
  {
    name: "Batco Transport Logistic",
    link: "batco-transport",
    url: "http://www.batco.in/",
  },
  {
    name: "First Flight Courier",
    link: "first-flight-courier-tracking",
    url: "https://www.firstflight.net/",
  },
  {
    name: "Suntek Axpress",
    link: "suntek-axpress-tracking",
    url: "https://suntekaxpress.in/",
  },
  {
    name: "JK Transport",
    link: "jk-transport-tracking",
    url: "http://jktransport.co.in/",
  },
  {
    name: "Relay Express",
    link: "relay-express-tracking",
    url: "https://www.relayexpress.in/",
  },
  {
    name: "Airwings Courier India",
    link: "airwings-courier-india-tracking",
    url: "http://www.airwingsindia.com/",
  },
  {
    name: "Shree Mahabali Courier",
    link: "mahabali-courier-express-tracking",
    url: "http://shreemahabaliexpress.com/",
  },
  {
    name: "OBN Tracking",
    link: "obn-courier-tracking",
    url: "https://www.obnexpress.com/",
  },
  {
    name: "Blue Sky Courier",
    link: "blue-sky-courier-tracking",
    url: "http://www.blueskycourier.co.in/",
  },
  {
    name: "Yes Courier",
    link: "yes-courier-tracking",
    url: "http://www.yescourier.in/",
  },
  {
    name: "Jaydeep Logistics",
    link: "jaydeep-logistics-tracking",
    url: "https://jaydeeplogistic.com/",
  },
  {
    name: "Som Logistics",
    link: "som-logistics-tracking",
    url: "https://www.slsindia.co.in/",
  },
  {
    name: "OnDot Courier",
    link: "ondot-courier-tracking",
    url: "http://ondotcouriers.co.in/",
  },
  {
    name: "ICC Worldwide Courier",
    link: "icc-worldwide-courier-tracking",
    url: "http://iccworld.com/",
  },
  {
    name: "Xspeed Logistics",
    link: "xpeed-logistics-tracking",
    url: "https://www.xpeed.in/",
  },
  {
    name: "Orange Cargo",
    link: "orange-cargo-carriers-tracking",
    url: "http://www.orangecargo.in/",
  },
  {
    name: "Vichare Courier",
    link: "vichare-courier-tracking",
    url: "https://vichare.com/",
  },
  {
    name: "Pavan Courier",
    link: "pavan-courier-tracking",
    url: "http://pavancourierservice.com/",
  },
  {
    name: "BMPS Tracking",
    link: "bmps-tracking",
    url: "http://www.bmps.co.in/",
  },
  {
    name: "SRMT Tracking",
    link: "srmt-tracking",
    url: "https://srmt.com/",
  },
  {
    name: "BSA Logistics",
    link: "bsa-logistics-tracking",
    url: "http://www.bsa.co.in/",
  },
  {
    name: "Simply Tracking",
    link: "simply-tracking",
    url: "https://www.simplylogistics.in/",
  },
  {
    name: "Mass Tracking",
    link: "mass-tracking",
    url: "https://meccargo.com/",
  },
  {
    name: "Onpoint Express",
    link: "onpoint-tracking",
    url: "https://onpoint.in/",
  },
  {
    name: "K D Courier",
    link: "k-d-courier-tracking",
    url: "https://kdcourier.com/",
  },
  {
    name: "Speed and Safe Courier",
    link: "speed-and-safe-courier-tracking",
    url: "https://www.gokulamspeedandsafe.com/",
  },
  {
    name: "DRTC Transport",
    link: "drtc-tracking",
    url: "https://www.drtctracking.com/",
  },
  {
    name: "Inland World Logistics",
    link: "inland-world-logistics-tracking",
    url: "https://www.inlandworldlogistics.com/",
  },
];
