export const courierUrls = {
  "4px-tracking": "",
  "abf-freight-tracking": "https://arcb.com/tools/tracking.html",
  "accurate-freight-carrier-tracking":
    "http://103.13.97.213/AFC/Home/Indexdocket",
  "ace-courier-tracking": "https://www.aceexpressindia.com",
  "afl-courier-tracking": "",
  "airpak-express-tracking": "https://airpak-express.com/index",
  "airstate-courier-tracking": "http://www.airstateindia.com/",
  "airwings-courier-tracking": "http://www.airwingsindia.com/tracking.html",
  "ajw-courier-tracking": "https://www.ajwex.com/",
  "akash-ganga-courier-tracking": "https://www.akashganga.info/",
  "anjani-courier-tracking": "http://www.shreeanjanicourier.com/",
  "apc-postal-tracking": "https://www.apc-pli.com/",
  "aramex-australia-tracking": "https://www.aramex.com.au/",
  "aramex-courier-tracking": "https://www.aramex.com/in/en/track/shipments",
  "arc-carrier-tracking": "https://online.arclimited.com/cnstrk/cnstrk.aspx",
  "asendia-usa-tracking": "https://www.asendiausa.com/",
  "amazon-transportation-servies-tracking": "https://track.amazon.in/",
  "ats-cargo-courier-tracking":
    "http://atscargo.erp.logibrisk.com/BookingTracking",
  "australia-post-tracking": "https://auspost.com.au/",
  "better-trucks-tracking": "https://www.bettertrucks.com/",
  "blazeflash-courier-tracking": "",
  "blue-dart-courier-tracking": "https://www.bluedart.com/",
  "bom-gim-courier-tracking": "https://www.bomgim.com/",
  "bombino-courier-tracking": "https://www.bombinoexp.com/en-in",
  "bonds-courier-tracking": "https://bondscouriers.com.au/",
  "bonds-logistics-courier-tracking": "https://bondscouriers.com.au/",
  "border-express-tracking": "https://www.borderexpress.com.au/",
  "brazil-correios-tracking": "https://www.correios.com.br/#",
  "canada-post-tracking":
    "https://www.canadapost-postescanada.ca/cpc/en/home.page",
  "cci-courier-tracking": "https://cci-logistics.com/",
  "china-post-tracking": "http://www.chinapost.com.cn/",
  "citipost-courier-tracking": "https://citipost.com/",
  "city-express-courier-tracking": "http://cityexpresscourierservice.com/",
  "city-link-express-tracking": "https://www.citylinkexpress.com/",
  "cj-packet-tracking": "https://cjpacket.com/",
  "cma-cgm-tracking": "https://www.cma-cgm.com/",
  "con-way-freight-tracking": "https://ext-web.ltl-xpo.com/landing",
  "connectindia-courier-tracking": "https://connectindia.com/tracking/",
  "corporate-courier-tracking": "http://www.corporatecourier.in/",
  "corporate-express-tracking":
    "http://authorcodesoftware.in/corporateexpress/newmastertracking.aspx",
  "courier-post-tracking":
    "https://trackandtrace.courierpost.co.nz/search/advanced/",
  "couriers-please-tracking": "https://www.couriersplease.com.au/",
  "delcart-courier-tracking": "http://www.delnetconnect.net/",
  "delex-courier-tracking": "https://www.delex.in/",
  "delhivery-courier-tracking": "https://www.delhivery.com/",
  "delnet-express-tracking": "http://www.delnetconnect.net/",
  "deutsche-post-dhl-tracking": "https://www.dhl.de/en/privatkunden.html",
  "dhl-active-tracking":
    "https://activetracing.dhl.com/DatPublic/datSelection.do",
  "dhl-courier-tracking": "https://www.dhl.com/in-en/home.html?locale=true",
  "dhl-ecommerce-asia-tracking":
    "https://www.dhl.com/in-en/home.html?locale=true",
  "dhl-express-tracking": "https://www.dhl.com/in-en/home.html?locale=true",
  "dhl-global-forwarding-tracking":
    "https://www.dhl.com/in-en/home.html?locale=true",
  "dhl-global-mail-tracking": "https://www.dhl.com/in-en/home.html?locale=true",
  "dhl-pieceid-tracking": "https://www.dhl.com/in-en/home.html?locale=true",
  "diacom-canada-tracking": "https://gls-canada.com/en/dicom/tracking",
  "digital-courier-tracking":
    "https://digitalcouriercargo.com/track-your-order/",
  "dotzot-courier-tracking": "https://dotzot.in/",
  "dpd-tracking": "https://www.dpd.com/en/",
  "dpd-uk-tracking": "https://www.dpd.co.uk/",
  "dpd-us-tracking": "https://www.dpd.com/en/",
  "drtc-courier-tracking": "https://www.dtdc.in/tracking.asp",
  "dtdc-australia-tracking":
    "https://www.dtdcaustralia.com.au/track-your-shipment/",
  "dtdc-express-global-tracking": "https://www.dtdc.in/tracking.asp",
  "dtdc-singapore-tracking": "https://singapore.dtdc.com/",
  "dtdc-uae-tracking": "https://uae.dtdc.com/",
  "dtdc-usa-tracking": "https://usa.dtdc.com/",
  "eagle-courier-tracking": "http://www.eaglelogistics.in/tracking.php",
  "ecom-express-courier-tracking": "https://ecomexpress.in/",
  "ekart-courier-tracking": "https://ekartlogistics.com/",
  "elbex-courier-tracking": "https://elbextrack.com/index.php/awb-tracking",
  "expressit-courier-tracking":
    "https://portal.expressitlogistics.com/xcelerator/clientportal/",
  "falcon-courier-tracking": "http://www.falconcourier.net/track.html",
  "fedex-cross-border-tracking": "https://www.fedex.com/en-us/tracking.html",
  "fedex-freight-tracking": "https://www.fedex.com/en-us/tracking.html",
  "fedex-india-courier-tracking": "https://www.fedex.com/en-in/home.html",
  "fedex-tracking": "https://www.fedex.com/en-us/tracking.html",
  "fedex-uk-tracking": "https://www.fedex.com/en-us/tracking.html",
  "fedex-us-tracking": "https://www.fedex.com/en-us/tracking.html",
  "first-flight-courier-tracking": "https://www.firstflight.net/",
  "flyking-courier-tracking": "https://www.flyking.in/",
  "garudavega-courier-tracking": "https://www.garudavega.com/",
  "gati-kwe-courier-tracking": "https://www.gatikwe.com/",
  "gdex-tracking": "https://gdexpress.com/",
  "gls-czech-republic-tracking": "https://gls-group.eu/CZ/en/parcel-tracking",
  "gls-tracking-tracking": "https://gls-group.eu/GROUP/en/parcel-tracking",
  "gms-express-courier-tracking": "https://gmsworldwide.com/",
  "gms-worldwide-tracking": "https://gmsworldwide.com/",
  "gojavas-courier-tracking": "http://gojavas.com/",
  "grand-slam-express-tracking": "http://www.grandslamexpress.in/Web/Track",
  "hermes-germany-tracking":
    "https://www.myhermes.de/empfangen/sendungsverfolgung/",
  "hermes-world-tracking": "https://www.evri.com/track-a-parcel",
  "ib-express-courier-tracking": "http://ibexpress.in/online-tracking.asp",
  "india-post-international-tracking":
    "https://www.indiapost.gov.in/vas/Pages/IndiaPostHome.aspx",
  "india-post-tracking":
    "https://www.indiapost.gov.in/vas/Pages/IndiaPostHome.aspx",
  "indiaontime-courier-tracking": "http://ibexpress.in/online-tracking.asp",
  "jaipur-golden-courier-tracking": "",
  "janco-ecommerce-tracking": "https://www.jancofreight.com/",
  "japan-post-tracking": "https://www.post.japanpost.jp/index.html",
  "jt-express-malaysia-tracking": "https://jtexpress.my/",
  "kerry-indev-express-tracking":
    "https://www.kerryindevexpress.com/track.aspx",
  "la-poste-tracking": "https://www.laposte.fr/outils/suivre-vos-envois",
  "lasership-courier-tracking": "https://www.ontrac.com/",
  "leopard-courier-tracking": "https://www.leopardscourier.com/",
  "lexship-courier-tracking": "https://track.lexship.com/",
  "madhur-courier-tracking":
    "https://www.madhurcouriers.in/(S(2r15y0s0xhah5ah3btfylzv1))/CNoteTracking",
  "malaysia-post-flexipack-tracking": "https://tracking.pos.com.my/tracking",
  "maruti-courier-tracking": "https://www.shreemaruticourier.com/",
  "metro-maruti-courier-tracking": "http://mmexcouriers.com/",
  "mirakle-courier-tracking": "https://www.miraklecouriers.com/track/",
  "nandan-courier-tracking": "http://www.shreenandancourier.com/",
  "new-zealand-post-tracking": "https://www.nzpost.co.nz/",
  "nextsmartship-tracking": "https://www.nextsmartship.com/",
  "nitco-courier-tracking": "https://www.nitcologistics.com/",
  "nova-poshta-international-tracking": "https://novaposhta.ua/",
  "nuvo-ex-courier-tracking": "http://www.nuvoex.com/",
  "old-dominion-tracking": "https://www.odfl.com/",
  "om-logistics-courier-tracking":
    "https://omsanchar.omlogistics.co.in/omcntrack/",
  "ondot-courier-tracking": "https://ondotcouriers.co.in/tracking.aspx",
  "overnite-courier-tracking": "https://www.overnitenet.com/",
  "overnite-express-courier-tracking":
    "https://trackcourier.in/track-overnite.php",
  "oxford-express-courier-tracking": "http://oxfordexp.com/Default.aspx",
  "pafex-courier-tracking": "http://cms.pafex.in/Query/TrackAwbNoQuery",
  "palande-courier-tracking": "",
  "pcs-express-courier-tracking": "http://www.pcsexp.in/tracking.html",
  "pegasus-courier-tracking": "https://www.pegasuscourierindia.com/",
  "pickrr-courier-tracking": "https://pickrr.com/track/",
  "pickspeed-courier-tracking": "https://trackcourier.in/track-overnite.php",
  "pigeon-courier-tracking": "https://www.pigeoncargo.com/",
  "pitney-bowes-tracking": "https://trackpb.shipment.co/track",
  "polar-express-tracking": "http://the-tracking.com/",
  "poonam-courier-tracking": "https://trackcourier.in/track-poonam.php",
  "poslaju-tracking": "https://www.pos.com.my/",
  "poste-italiane-tracking": "https://www.poste.it/",
  "procure-logistics-tracking": "",
  "professional-courier-tracking": "https://www.tpcindia.com/Default.aspx",
  "professional-kuwait-tracking": "https://www.tpcindia.com/Default.aspx",
  "professional-singapore-tracking": "https://www.tpcindia.com/Default.aspx",
  "professional-srilanka-tracking": "https://www.tpcindia.com/Default.aspx",
  "professional-uae-tracking": "https://www.tpcindia.com/Default.aspx",
  "professional-usa-tracking": "https://www.tpcindia.com/Default.aspx",
  "procure-courier-tracking": "http://www.procurelogistics.com/",
  "purolator-tracking": "https://www.purolator.com/en",
  "pushpak-courier-tracking": "https://www.pushpakcourier.net/query.php",
  "quantium-courier-tracking": "http://track.quantiumsolutions.com/",
  "rapid-delivery-tracking": "https://rapiddelivery.co/",
  "rapidconnect-tracking": "https://trackcourier.in/track-rapidconnect.php",
  "red-express-tracking": "https://redxpress.in/Index#testimonial",
  "registered-post-tracking": "https://www.indiapost.gov.in/",
  "rivigo-courier-tracking": "https://rivigo.com/",
  "rl-carriers-tracking": "https://www2.rlcarriers.com/",
  "roadrunner-frieght-tracking":
    "https://freight.rrts.com/Tools/Tracking/Pages/default.aspx?__hstc=248371416.07c99ad66162c0426da608c25893fc6a.1687236830765.1687236830765.1687236830765.1&__hssc=248371416.1.1687236830766&__hsfp=2089710868",
  "safexpress-courier-tracking": "http://www.safexpress.com/",
  "safexpress-india-tracking": "http://www.safexpress.com/",
  "sagawa-courier-tracking": "https://www.sagawa-exp.co.jp/",
  "saia-courier-tracking": "https://www.saia.com/home",
  "sameday-courier-tracking": "https://sameday.ro/",
  "saudi-post-tracking": "https://splonline.com.sa/ar/",
  "scudex-express-courier-tracking":
    "https://www.aftership.com/carriers/scudex-express",
  "shadowfax-courier-tracking": "https://www.shadowfax.in/track-order",
  "shipdelight-courier-tracking": "https://track.shipdelight.com/",
  "shiprocket-courier-tracking": "https://www.shiprocket.in/shipment-tracking/",
  "shree-anjani-courier-tracking": "http://www.shreeanjanicourier.com/",
  "shree-balaji-courier-tracking":
    "http://ww1.shreebalajifastcourierandcargo.in/",
  "shree-mahavir-courier-tracking": "http://shreemahavircourier.com/",
  "shree-maruti-courier-tracking": "https://www.shreemaruticourier.com/",
  "shree-tirupati-courier-tracking": "http://www.shreetirupaticourier.net/",
  "sigma-courier-tracking": "https://trackcourier.in/track-sigma.php",
  "skyking-courier-tracking": "https://skyking.co/#",
  "skyman-courier-tracking": "http://skymanairexpress.com/track.aspx",
  "skynet-australia-tracking": "https://www.skynet.net/australia",
  "skynet-courier-tracking": "https://www.skynetworldwide.com/tracking.html",
  "skynet-germany-tracking": "https://www.skynetworldwide.com/tracking.html",
  "skynet-india-tracking": "http://skynetindia.com/",
  "skynet-malaysia-tracking": "https://www.skynet.com.my/",
  "skynet-mexico-tracking": "https://www.skynet.net/mexico",
  "skynet-nigeria-tracking": "https://skynetworldwide.com.ng/tracking/",
  "skynet-pakistan-tracking": "https://www.skynet.net/pakistan",
  "skynet-philippines-tracking": "https://www.skynet.net/philippines",
  "skynet-singapore-tracking": "https://www.skynet.net/singapore",
  "skynet-uae-tracking": "https://www.skynetworldwide.net/",
  "skynet-usa-tracking": "https://www.skynet.net/USA",
  "skynet-yemen-tracking": "https://www.skynet.net/yemen",
  "smsa-express-tracking": "https://www.smsaexpress.com/in",
  "spee-dee-delivery-tracking": "https://speedeedelivery.com/track-a-shipment/",
  "speed-&-safe-courier-tracking":
    "https://www.gokulamspeedandsafe.com/speedandsafe-tracking/",
  "speed-post-tracking":
    "https://www.indiapost.gov.in/vas/Pages/IndiaPostHome.aspx",
  "spoton-courier-tracking": "https://web1.spoton.co.in/",
  "st-courier-tracking": "http://stcourier.com/",
  "swiss-post-tracking": "https://www.post.ch/de",
  "target-courier-tracking": "https://trackcourier.in/track-target.php",
  "tci-express-courier-tracking":
    "https://www.tciexpress.in/trackingdocket.aspx",
  "tci-freight-courier-tracking":
    "https://www.tcifreight.in/track-consignment.html",
  "tcs-courier-tracking": "https://www.tcsexpress.com/",
  "tej-courier-tracking":
    "http://erp.tejcouriers.in:2020/Reports/CnsmntStatusRpt/CnoteStatus.aspx?",
  "tirupati-courier-tracking": "http://www.shreetirupaticourier.net/",
  "tnt-courier-tracking": "https://www.tnt.com/express/en_in/site/home.html",
  "tnt-reference-tracking":
    "https://www.tnt.com/express/en_in/site/shipping-tools/tracking.html?utm_redirect=legacy_track&navigation=1&respLang=en",
  "tnt-uk-tracking": "https://www.tnt.com/express/en_in/site/home.html",
  "trackon-courier-tracking": "https://trackon.in/",
  "ubx-courier-tracking":
    "http://www.ubxpress.com/in/tracking/tracking_page1.aspx",
  "united-courier-tracking": "http://unitedcouriers.biz/Track.aspx",
  "ups-courier-tracking": "https://www.ups.com/us/en/Home.page",
  "usps-courier-tracking": "https://www.usps.com/",
  "v-xpress-courier-tracking": "https://www.vxpress.in/",
  "vichare-courier-tracking": "https://www.vichare.com/",
  "vrl-logistics-courier-tracking":
    "https://www.vrlgroup.in/track_consignment.aspx",
  "vtrans-courier-tracking": "https://vtransgroup.com/",
  "vulcan-courier-tracking": "https://trackshipment.vulcanxpreess.com/",
  "winit-courier-tracking": "https://winit.com.cn/",
  "wow-express-courier-tracking": "https://wowexpress.co/",
  "xpressbees-courier-tracking": "https://www.xpressbees.com/",
  "xps-courier-tracking": "https://trackcourier.in/track-xps.php",
  "yamato-japan-tracking": "https://www.kuronekoyamato.co.jp/ytc/customer/",
  "yrc-Frieght-tracking": "https://yrc.com/",
  "yun-express-tracking": "https://www.yunexpress.com/",
  "zto-express-tracking": "https://www.zto.com/",
};
