export const keywords = {
    homepage:["courier tracking",
    "package tracking",
    "shipment tracking",
    "parcel tracking",
    "tracking number",
    "tracking ID",
    "courier provider",
    "delivery status",
    "tracking status",
    "real-time updates",
    "international tracking",
    "domestic tracking",
    "express courier tracking",
    "logistics tracking",
    "tracking information",
    "tracking tool",
    "online tracking",
    "courier service tracking",
    "track and trace",
    "track shipment",
    "track parcel",
    "track consignment",
    "4PX tracking",
"Accurate Freight Carrier tracking",
"Anjani Courier tracking",
"Aramex Australia tracking",
"ARC Carrier tracking",
"ATS Amazon Shipping tracking",
"Better Trucks tracking",
"Bonds Courier tracking",
"Blue Dart Courier tracking",
"City-Link Express tracking",
"Con-way Freight tracking",
"Courier Post tracking",
"CJ Packet tracking",
"Delex Courier tracking",
"DHL Active Tracing tracking",
"DHL Ecommerce Asia tracking",
"DHL Express Piece ID tracking",
"DHL Global Mail tracking",
"Dotzot Courier tracking",
"DPD UK tracking",
"DTDC tracking",
"DTDC Australia tracking",
"DTDC UAE tracking",
"Ecom Express Courier tracking",
"FedEx India tracking",
"FedEx Freight tracking",
"FedEx US tracking",
"First Flight Courier tracking",
"GarudaVega Courier tracking",
"Gati KWE Courier tracking",
"GLS tracking",
"GMS Worldwide Courier tracking",
"Hermes Germany tracking",
"India Post Domestic tracking",
"Jaipur Golden tracking",
"Japan Post tracking",
"La Poste tracking",
"Leopard Courier tracking",
"Madhur Courier tracking",
"Maruti Courier tracking",
"New Zealand Post tracking",
"NITCO Roadways tracking",
"NuvoEx Courier tracking",
"Om Logistics tracking",
"Pickrr Courier tracking",
"Polar Express tracking",
"Poste Italiane tracking",
"Professional Courier Kuwait tracking",
"Professional Courier SriLanka tracking",
"Professional Courier USA tracking",
"Purolator tracking",
"Roadrunner Freight tracking",
"Safexpress India Courier tracking",
"Safexpress Logistics tracking",
"Sagawa Express tracking",
"South African Post Office tracking",
"TNT tracking",
"Transglobal Express tracking",
"UPS Mail Innovations tracking",
"USPS tracking",
"V-Xpress tracking",
"XPO Logistics tracking",
"Yamato Japan tracking",
"YRC Freight tracking"],

    courierProviderPage:[
    "tracking",
    "courier tracking",
    "package tracking",
    "shipment tracking",
    "parcel tracking",
    "consignment tracking",
    "courier",
    "courier track",
    "track",
    "tracking number",
    "tracking ID",
    "courier provider",
    "delivery status",
    "tracking status",
    "courier real-time updates",
    "logistics tracking",
    "tracking information",
    "tracking tool",
    "online tracking",
    "courier service",
    "track and trace",
    "track shipment",
    "track parcel",
    "track package",
    "track courier",
    ]
}